[config]
title = "demo_title"
type = "demo_type"

[content]
line_a = "demo_line_a"
line_b = "demo_line_b"

[choices]
# Name / Condition / Action
choice_a = ["choice_a", "is_player_alive", "kill_player"]
