[config]
name = "C_1_s_22"
type = "default"
[content]
1 = "Looking at Izydor he says ''It all started a Year ago in 1972 if you didn't know because you seem lost in time. In one week all the city was in chaos, dead bodies everywhere in the street. but now it's different...''"
2 = ""
3 = "---"
[choices]
1 = [" Next", "true", "C_1_s_25"]
