[config]
name = "C_1_s_26"
type = "default"
[content]
1 = "Izydor move in the asylum and exit finding other strangers outside, the other looks Izydor and talked together ''who the fuck is this? you find a man in this building.''"
2 = ""
3 = "The other says ''yea he is lost and he doesn't even know what's going on here, I wasn't gonna leave him alone to die! We'll take him to HQ and see later.''"
4 = ""
5 = "---"
[choices]
1 = [" Next", "true", "C_1_s_27"]
