[config]
name = "C_2_s_2"
type = "default"
[content]
1 = "After a 30 min walk, Izydor arrives in front of a drug store, the city is exactly as the group had presented it."
2 = ""
3 = "The drug store is located in a district with houses which all seems more empty one than the other, no cars at the horizon, the grass is dead near Izydor, the nature seems to die just like the city."
4 = ""
5 = "After contemplating you walk toward the entrance of the drug store, two people of the group are with you; Norbert and Dagmara."
6 = ""
7 = "---"
[choices]
1 = [" Go in to find some supplies", "true", "C_2_s_3"]
2 = [" Talk with Norbert", "true", "C_2_s_6"]
3 = [" Talk with Dagmara", "true", "C_2_s_5"]
