[config]
name = "Great Page"
type = "default"
[content]
1 = "Izydor drinks down one of his bottles of potato vodka."
2 = "He starts to talk about his years of being a farmer in his quiet farm far from everything."
3 = "Then bragging about his unique alcohol recipe."
4 = ""
5 = "---"
[choices]
1 = [" A troop of the Rosyjski spotted you!", "true", "C_3_s_28"]
