[config]
name = "C_4_s_38"
type = "default"
[content]
1 = "Izydor decide to sleep inside the bus alone, pretending to keep an eye on the bus."
2 = "Everybody agreed that nobody would try to steal a bus from him."
3 = ""
4 = "But he was feeling uncomfortable with Dagmara since he found her wounded."
5 = ""
6 = "The next day morning..."
7 = ""
8 = "---"
[choices]
1 = [" He repair the bus and leave alone", "true", "C_4_s_39"]
2 = [" He repair and goes to wake up the group", "true", "C_4_s_40"]
3 = [" He goes to meet the group inside the house", "true", "C_4_s_42"]
