[config]
name = "C_4_s_14"
type = "default"
[content]
1 = "Izydor take the first person infront him and use it as a shield to protect himself outside the bus."
2 = "Unfortunately this terrible idea fail and Izydor get killed aswell."
3 = ""
4 = "At the same time the monster entered inside the bus killing the last member of the group alive."
5 = ""
6 = "---"
[choices]
1 = [" The End", "true", "recap"]
