[config]
name = "C_4_s_27"
type = "default"
[content]
1 = "After exploding the bus attract a massive horde of monsters."
2 = "The group managed to enter inside an abbandoned house but are now stuck inside."
3 = ""
4 = "Izydor is feeling heroic."
5 = ""
6 = "---"
[choices]
1 = [" Last Stand", "true", "C_4_s_28"]
