[config]
name = "Milestone 3 Build"
type = "default"
[content]
greatings = "Happy to see you !"
explanation_a = "Welcome to the example of the game !  We will explain you everything about the game."
[choices]
start = ["Start", "true", "start"]
