[config]
name = "C_0_s_4"
type = "default"
[content]
1 = "''How dare you insult me like this, when all you do is fucking nothing except lay around at home, you better get out of here before I punch you in the face! I drink as much as I want, it's my alcohol I do what I want with it!''"
2 = ""
3 = "Izydor gets closer to his wife while being very menacing and hits his wife making her fall on the ground."
4 = ""
5 = "---"
[choices]
1 = [" Next", "true", "C_1_s_1"]
