[config]
name = "C_1_s_25"
type = "default"
[content]
1 = "When you talk with the stranger, you hear someone screaming ''Hey guys we need to move, we are losing time here we found nothing, go back to the entryway we will move together!'' "
2 = ""
3 = "He says ''you stay here or do you come with us? Staying here is a good way to die and I don't want to have your death on my consciousness, so follow us.''"
4 = ""
5 = "---"
[choices]
1 = [" Next", "true", "C_1_s_26"]
