[config]
name = "C_1_s_26"
type = "default"
[content]
1 = "Izydor moves in the asylum and exit the building finding other strangers outside, the others look Izydor and argues with the rest of the group '' Who the fuck is this? You found a man in this building, why did you bring him with you?''."
2 = ""
3 = "The others say ''Yeah, he is lost and he doesn't even know what's going on here, I wasn't gonna leave him alone to die! We'll take him to HQ and see later.''"
4 = ""
5 = "---"
[choices]
1 = [" Next", "true", "C_1_s_27"]
