[config]
name = "C_1_s_17"
type = "default"
[content]
1 = "The stranger lays his bat on the wall near him, taking a breath and responds."
2 = ""
3 = "''Many things but everyone thinks something different, for some it's war again,for others politics, some even are talking about aliens but it's complicated to know who is right.''"
4 = ""
5 = "---"
[choices]
1 = ["When did this happen?", "true", "C_1_s_22"]
2 = [" Where is everybody?", "true", "C_1_s_21"]
