[config]
name = "C_1_s_23"
type = "default"
[content]
1 = "The stranger looks Izydor in the eye and says ''Maybe, but I don't know you so even if I knew one I will not take you to her actually, I think you will understand you seem like a good guy!''"
2 = ""
3 = "---"
[choices]
1 = [" Next", "true", "C_1_s_25"]
