[config]
name = "C_1_s_19"
type = "default"
[content]
1 = "The stranger talks to Izydor ''I'm sorry for you but everyone here is either dead or has left long ago, if you want to find one you will have to go into the city but it's dangerous there''"
2 = ""
3 = "Looking at Izydor the stranger says ''But you seem very strong so I think you will survive, don't worry''"
4 = ""
5 = "---"
[choices]
1 = ["When did this happened", "true", "C_1_s_22"]
2 = ["Do you know someone who is a doctor?", "true", "C_1_s_23"]
