[config]
name = "C_1_s_3"
type = "default"
[content]
1 = "Looking around him, Izydor finds cars and trash cans, the cars are full of dust and moss, after some seconds of hesitation he searches in the nauseating bins, but unfortunately their is nothing inside."
2 = ""
3 = "After another look Izydor find a door on the side of the building. This one seems to be the emergency exit, the door is metal but looks fragile, it must be rusty and nobody thought about fixing it. "
4 = ""
5 = "---"
[choices]
1 = [" Force the exit door", "true", "C_1_s_4"]
2 = [" Enter inside the building", "true", "C_1_s_2"]
