[config]
name = "C_2_s_14"
type = "default"
[content]
1 = "Izydor decides to learn more about him, he asks him how his life was before the disaster."
2 = ""
3 = "Stefan replied ''I used to live in the forest far enough away from here was throwing trapper I lived like you what, I hunted I farmed, but at some point my daughter got seriously ill so I went into town to stay with her and care for her, after you know the rest... the destruction of the city''"
4 = ""
5 = "---"
[choices]
1 = [" Go in to find some supplies", "true", "C_2_s_9"]
2 = [" Talk with Zenon", "true", "C_2_s_10"]
