[config]
name = "C_3_s_29"
type = "default"
[content]
1 = "In few seconds the group gets surrounded by the Rosyjski troops aiming guns at you, yelling at you to freeze."
2 = ""
3 = "They have no choice to wait and cooperate."
4 = "Dagmara doesn't seem to feel well."
5 = ""
6 = "---"
[choices]
1 = [" Cover Dagmara", "true", "C_3_s_35"]
2 = [" Do nothing", "true", "C_3_s_34"]
