[config]
name = "C_4_s_24"
type = "default"
[content]
1 = "Norbert take the control of the bus and ask to Izydor to carry the road map to lead them to the airport."
2 = ""
3 = "The road is full of car wreck but Norbert is a good driver but he has to dodge a lot of them."
4 = "The next branch they..."
5 = ""
6 = "---"
[choices]
1 = [" Turn left", "true", "C_4_s_25"]
2 = [" Turn right", "true", "C_4_s_34"]
