[config]
name = "C_4_s_41"
type = "default"
[content]
1 = "He ran back to the bus and leave the area."
2 = "The moving dead bodies of it's mates were dissapearing at the horizon."
3 = ""
4 = "He decided to go back to it's farm."
5 = ""
6 = "---"
[choices]
1 = [" The End", "true", "recap"]
