[config]
name = "C_4_s_7"
type = "default"
[content]
1 = "Asking them to wait him, Izydor still struggle to push away the monsters."
2 = "During that fight, one of them sneaked into the bus creating the chaos and made the group of survivor crash the bus again."
3 = ""
4 = "Everybody died."
5 = ""
6 = "---"
[choices]
1 = [" The End", "true", "recap"]
