[config]
name = "Milestone 3 Build"
type = "Save"
[content]
greatings = "Happy to see you !"
explanation_a = "AAAAAAA BBBBBBBBBBBBB CCCCCCCCCCCCCCC DDDDDDDDDDDDDDDDD AAAAAAA BBBBBBBBBBBBB CCCCCCCCCCCCCCC DDDDDDDDDDDDDDDDD AAAAAAA BBBBBBBBBBBBB CCCCCCCCCCCCCCC DDDDDDDDDDDDDDDDD AAAAAAA BBBBBBBBBBBBB CCCCCCCCCCCCCCC DDDDDDDDDDDDDDDDD"
great_line = "---"
[choices]
start = ["Start", "true", "start"]
