[config]
name = "Milestone 3 Build"
type = "Save"
[content]
greatings = "Happy to see you !"
explanation_a = "Welcome ${included_variable} 35?35 35$ to the ''example'' $(included_variable = 0; included_variable < 0) { ${included_variable} -10 => true} $(included_variable = 0; included_variable < 0){-10 => true} of the game !  We will explain you everything about the game. Other great Text !"
great_line = "---"
[choices]
start = ["Start", "true", "start"]
start = ["Start", "true", "start"]
start = ["Start", "true", "start"]
start = ["Start", "true", "start"]
