[config]
name = "Example"
author = "unknow"
tags = ["edited", "client-0.3.0"]
[data]
done_data_page = 0
page_count = 0
recap_Number_Of_People_Killed = 10
recap_Player_LIfe = -55
included_variable = -10
console_color_selected_button_locked_background = 41
console_color_selected_button_locked_foreground = 37
console_color_selected_button_background = 47
console_color_selected_button_foreground = 33
console_color_button_background = 46
console_color_button_foreground = 30
[conditions]
true = ["1 = 1"]
have_done_data_page = ["done_data_page > page_count"]
false = ["1 > 1"]
have_not_done_data_page = ["done_data_page < 1"]
[actions]
start = ["$cond.toml"]
data = ["$data.toml"]
done_data = ["done_data_page + 1", "$cond.toml "]
final = ["$final.toml"]
restart = ["$index.toml"]
[client]
page = "pages/index.toml"
frameSize_x = 100
frameSize_y = 25
up = 72
down = 80
ok = 13
zoom = 61
unzoom = 45
exit = 27
