[config]
name = "projectName"
author = "unknow"
tags = ["edited", "v0.3.0"]
[data]
[conditions]
true = ["1 = 1"]
[actions]
nothing = ["$index.toml"]
[client]
page = "pages/index.toml"
frameSize_x = 100
frameSize_y = 10
up = 72
down = 80
ok = 13
zoom = 61
unzoom = 45
exit = 27
