[config]
name = "Izydor_V1.0"
author = "BG4"
tags = ["edited", "client-0.3.0"]
[data]
done_data_page = 0
page_count = 0
console_color_background = 47
console_color_foreground = 30
vodka = 0
karma = 0
norb = 1
dagm = 1
morphia = 0
text_noise_level = 0
c_karma = 0
medkit = 0
v_noise = 10
recap_vodka = 0
recap_morphia = 0
recap_karma = 0
[conditions]
true = ["1 = 1"]
c_morphia = ["morphia > 0"]
c_vodka = ["vodka > 0"]
c_good = ["karma > 0"]
c_bad = ["karma < 0"]
[actions]
restart = ["$index.toml"]
start = ["$tuto.toml"]
C_0_s_1 = ["$C_0_s_1.toml"]
C_0_s_2 = ["$C_0_s_2.toml"]
goodstart = ["morphia + 3", "vodka + 1", "$C_0_s_3.toml"]
badstart = ["morphia + 2", "vodka + 3", "$C_0_s_4.toml"]
C_1_s_1 = ["$C_1_s_1.toml"]
C_1_s_2 = ["$C_1_s_2.toml"]
C_1_s_3 = ["$C_1_s_3.toml"]
C_1_s_8 = ["$C_1_s_8.toml"]
C_1_s_6 = ["$C_1_s_6.toml"]
C_1_s_7 = ["$C_1_s_7.toml"]
C_1_s_4 = ["$C_1_s_4.toml"]
C_1_s_5 = ["$C_1_s_5.toml"]
C_1_s_9 = ["$C_1_s_9.toml"]
C_1_s_10 = ["$C_1_s_10.toml"]
C_1_s_12 = ["$C_1_s_12.toml"]
C_1_s_11 = ["$C_1_s_11.toml"]
C_1_s_16 = ["$C_1_s_16.toml", "karma - 1"]
C_1_s_13 = ["$C_1_s_13.toml"]
C_1_s_14 = ["$C_1_s_14.toml"]
C_1_s_15 = ["$C_1_s_15.toml", "karma - 1"]
C_1_s_6_med = ["$C_1_s_6.toml", "medkit + 1"]
C_1_s_7_vodka = ["$C_1_s_7.toml", "vodka + 1"]
C_1_s_8_morphia = ["$C_1_s_8.toml", "morphia + 1"]
C_1_s_24 = ["$C_1_s_24.toml", "karma - 1", "text_noise_level = 0"]
C_1_s_20 = ["$C_1_s_20.toml", "text_noise_level = 0"]
C_1_s_18 = ["$C_1_s_18.toml"]
C_1_s_17 = ["$C_1_s_17.toml"]
C_1_s_19 = ["$C_1_s_19.toml"]
C_1_s_22 = ["$C_1_s_22.toml"]
C_1_s_21 = ["$C_1_s_21.toml"]
C_1_s_23 = ["$C_1_s_23.toml"]
C_1_s_25 = ["$C_1_s_25.toml"]
C_1_s_26 = ["$C_1_s_26.toml"]
C_1_s_27 = ["$C_1_s_27.toml"]
C_3_s_2 = ["$C_3_s_2.toml", "karma + 1"]
C_3_s_3 = ["$C_3_s_3.toml"]
C_3_s_5 = ["$C_3_s_5.toml", "vodka - 1", "karma + 1"]
C_3_s_4 = ["$C_3_s_4.toml"]
C_3_s_6 = ["$C_3_s_6.toml"]
C_3_s_12_gcat = ["$C_3_s_12.toml", "karma + 1"]
C_3_s_7 = ["$C_3_s_7.toml", "karma - 2"]
C_3_s_8 = ["$C_3_s_8.toml"]
C_3_s_9 = ["$C_3_s_9.toml"]
C_3_s_10 = ["$C_3_s_10.toml", "karma + 1"]
C_3_s_12_bcat = ["$C_3_s_12.toml", "karma - 1"]
C_3_s_14 = ["$C_3_s_14.toml", "karma - 2"]
C_3_s_11 = ["$C_3_s_11.toml", "karma + 1"]
C_3_s_12_use = ["$C_3_s_12.toml", "text_noise_level = v_noise"]
C_3_s_12_keep = ["$C_3_s_12.toml", "morphia + 1"]
C_3_s_12_refuse = ["$C_3_s_12.toml"]
C_3_s_12_bag = ["$C_3_s_12.toml", "morphia + 1", "karma + 1"]
C_3_s_12_together = ["$C_3_s_12.toml", "karma + 1"]
C_3_s_13 = ["$C_3_s_13.toml", "karma - 1"]
C_3_s_12 = ["$C_3_s_12.toml"]
C_3_s_31 = ["$C_3_s_31.toml"]
C_3_s_16 = ["$C_3_s_16.toml", "karma + 1"]
C_3_s_17 = ["$C_3_s_17.toml"]
C_3_s_19 = ["$C_3_s_19.toml", "morphia + 1"]
C_3_s_18 = ["$C_3_s_18.toml", "karma - 1"]
C_3_s_20 = ["$C_3_s_20.toml", "karma + 1"]
C_3_s_26 = ["$C_3_s_26.toml"]
C_3_s_25 = ["$C_3_s_25.toml", "vodka - 1", "karma + 1"]
C_3_s_24 = ["$C_3_s_24.toml", "vodka - 1", "karma - 1"]
C_3_s_21 = ["$C_3_s_21.toml"]
C_3_s_22 = ["$C_3_s_22.toml", "karma - 1"]
C_3_s_23_vodka = ["$C_3_s_23.toml", "karma + 2", "vodka - 1"]
C_3_s_23_morphia = ["$C_3_s_23.toml", "karma + 1", "morphia - 1"]
C_3_s_30 = ["$C_3_s_30.toml", "karma + 1"]
C_3_s_27 = ["$C_3_s_27.toml", "karma + 2"]
C_3_s_28 = ["$C_3_s_28.toml"]
C_3_s_37 = ["$C_3_s_37.toml", "dagm = 0"]
C_3_s_39_morphia = ["$C_3_s_39.toml", "morphia - 1", "text_noise_level = v_noise"]
C_3_s_29 = ["$C_3_s_29.toml", "karma - 1"]
C_3_s_35 = ["$C_3_s_35.toml", "karma + 1"]
C_3_s_34 = ["$C_3_s_34.toml"]
C_3_s_29_vodka = ["$C_3_s_29.toml", "vodka - 1", "karma + 1"]
C_3_s_39 = ["$C_3_s_39.toml"]
C_3_s_37_giveall = ["$C_3_s_37.toml", "morphia = 0", "dagm = 0"]
C_3_s_32_vodka = ["$C_3_s_32.toml", "vodka - 1"]
C_3_s_32 = ["$C_3_s_32.toml"]
C_3_s_33 = ["$C_3_s_33.toml"]
C_3_s_36 = ["$C_3_s_36.toml", "karma + 1"]
C_3_s_40 = ["$C_3_s_40.toml", "karma - 2", "norb = 0"]
C_3_s_37_hold = ["$C_3_s_37.toml", "karma + 1", "dagm = 0"]
C_3_s_39_giveall = ["$C_3_s_39.toml", "morphia = 0"]
C_3_s_39_vodka = ["$C_3_s_39.toml", "vodka - 1"]
C_3_s_38 = ["$C_3_s_38.toml"]
C_3_s_37_morphia = ["$C_3_s_37.toml", "morphia - 1", "dagm = 0"]
C_2_s_1 = ["$C_2_s_1.toml"]
C_2_s_2 = ["$C_2_s_2.toml"]
C_2_s_9 = ["$C_2_s_9.toml"]
C_2_s_10 = ["$C_2_s_10.toml"]
C_2_s_11 = ["$C_2_s_11.toml"]
C_2_s_13 = ["$C_2_s_13.toml"]
C_2_s_14 = ["$C_2_s_14.toml"]
C_2_s_12 = ["$C_2_s_12.toml"]
C_2_s_30 = ["$C_2_s_30.toml"]
C_2_s_17 = ["$C_2_s_17.toml"]
C_2_s_18 = ["$C_2_s_18.toml"]
C_2_s_19 = ["$C_2_s_19.toml"]
C_2_s_20 = ["$C_2_s_20.toml", "karma + 1 "]
C_2_s_21 = ["$C_2_s_21.toml", "karma - 1"]
C_2_s_24 = ["$C_2_s_24.toml"]
C_2_s_25 = ["$C_2_s_25.toml", "karma - 1"]
C_2_s_26 = ["$C_2_s_26.toml", "text_noise_level = 0"]
C_3_s_1 = ["$C_3_s_1.toml"]
C_3_s_15 = ["$C_3_s_15.toml"]
C_2_s_5 = ["$C_2_s_5.toml"]
C_2_s_6 = ["$C_2_s_6.toml"]
C_2_s_8 = ["$C_2_s_8.toml"]
C_2_s_7 = ["$C_2_s_7.toml"]
C_2_s_3 = ["$C_2_s_3.toml"]
C_2_s_15 = ["$C_2_s_15.toml", "karma - 1", "text_noise_level = v_noise"]
C_2_s_16 = ["$C_2_s_16.toml", "karma + 1"]
C_2_s_4 = ["$C_2_s_4.toml"]
C_2_s_29 = ["$C_2_s_29.toml"]
C_2_s_22 = ["$C_2_s_22.toml", "karma - 1", "text_noise_level = 0"]
C_2_s_23 = ["$C_2_s_23.toml", "text_noise_level = 0"]
C_1_s_8_drug = ["$C_1_s_8.toml", "text_noise_level = v_noise"]
C_4_s_3 = ["$C_4_s_3.toml"]
C_4_s_2 = ["$C_4_s_2.toml"]
C_4_s_8 = ["$C_4_s_8.toml"]
C_4_s_4 = ["$C_4_s_4.toml"]
C_4_s_5 = ["$C_4_s_5.toml"]
C_4_s_6 = ["$C_4_s_6.toml"]
C_4_s_7 = ["$C_4_s_7.toml"]
C_4_s_12 = ["$C_4_s_12.toml", "vodka - 1"]
C_4_s_10 = ["$C_4_s_10.toml"]
C_4_s_17 = ["$C_4_s_17.toml", "karma - 1"]
C_4_s_11 = ["$C_4_s_11.toml"]
C_4_s_13 = ["$C_4_s_13.toml"]
C_4_s_16 = ["$C_4_s_16.toml"]
C_4_s_14 = ["$C_4_s_14.toml"]
C_4_s_15 = ["$C_4_s_15.toml", "morphia - 1"]
C_4_s_19 = ["$C_4_s_19.toml"]
C_4_s_18 = ["$C_4_s_18.toml"]
C_4_s_21 = ["$C_4_s_21.toml"]
C_4_s_24 = ["$C_4_s_24.toml"]
C_4_s_22 = ["$C_4_s_22.toml", "vodka -1"]
C_4_s_25 = ["$C_4_s_25.toml"]
C_4_s_23 = ["$C_4_s_23.toml"]
C_4_s_34 = ["$C_4_s_34.toml"]
C_4_s_26 = ["$C_4_s_26.toml"]
C_4_s_27 = ["$C_4_s_27.toml"]
C_4_s_28 = ["$C_4_s_28.toml"]
C_4_s_29 = ["$C_4_s_29.toml"]
C_4_s_31 = ["$C_4_s_31.toml"]
C_4_s_30 = ["$C_4_s_30.toml"]
C_4_s_33 = ["$C_4_s_33.toml"]
C_4_s_32 = ["$C_4_s_32.toml"]
C_4_s_36 = ["$C_4_s_36.toml"]
C_4_s_47 = ["$C_4_s_47.toml"]
C_4_s_38 = ["$C_4_s_38.toml"]
C_4_s_37 = ["$C_4_s_37.toml"]
C_4_s_39 = ["$C_4_s_39.toml"]
C_4_s_40 = ["$C_4_s_40.toml"]
C_4_s_42 = ["$C_4_s_42.toml"]
C_4_s_44 = ["$C_4_s_44.toml", "morphia - 1", "text_noise_level = v_noise"]
C_4_s_43 = ["$C_4_s_43.toml"]
C_4_s_41 = ["$C_4_s_41.toml"]
C_4_s_45 = ["$C_4_s_45.toml", "text_noise_level = 0"]
C_4_s_46 = ["$C_4_s_46.toml", "text_noise_level = 0", "morphia - 1"]
C_4_s_1 = ["$C_4_s_1.toml", "text_noise_level = 0"]
C_4_s_20 = ["$C_4_s_20.toml"]
C_4_s_35 = ["$C_4_s_35.toml", "text_noise_level = 0"]
C_4_s_9 = ["$C_4_s_9.toml"]
C_2_s_27 = ["$C_2_s_27.toml"]
recap = ["$recap.toml"]
recap2 = ["$recap2.toml", "recap_vodka = vodka", "recap_morphia = morphia", "recap_karma = karma"]
credit = ["$credit.toml"]
[client]
page = "pages/C_4_s_3.toml"
frameSize_x = 115
frameSize_y = 30
up = 72
down = 80
ok = 13
zoom = 61
unzoom = 45
exit = 27
frame_size_min_x = 25
frame_size_min_y = 25
