[2023-01-24 16:41:41]
SAVE_PAGE = "pages/index.toml"
done_data_page = 1
page_count = 0
console_color_background = 47
recap_Number_Of_People_Killed = 10
recap_Player_LIfe = -55
included_variable = -10
[2023-01-24 16:41:42]
SAVE_PAGE = "pages/index.toml"
done_data_page = 1
page_count = 0
console_color_background = 47
recap_Number_Of_People_Killed = 10
recap_Player_LIfe = -55
included_variable = -10
[2023-01-24 16:56:40]
SAVE_PAGE = "pages/index.toml"
done_data_page = 1
page_count = 0
console_color_background = 47
recap_Number_Of_People_Killed = 10
recap_Player_LIfe = -55
included_variable = -10
[2023-01-24 16:56:41]
SAVE_PAGE = "pages/index.toml"
done_data_page = 1
page_count = 0
console_color_background = 47
recap_Number_Of_People_Killed = 10
recap_Player_LIfe = -55
included_variable = -10
[2023-01-24 18:07:13]
SAVE_PAGE = "pages/index.toml"
done_data_page = 0
page_count = 0
console_color_background = 47
recap_Number_Of_People_Killed = 10
recap_Player_LIfe = -55
included_variable = -10
[2023-01-24 18:08:14]
SAVE_PAGE = "pages/index.toml"
done_data_page = 0
page_count = 0
console_color_background = 47
recap_Number_Of_People_Killed = 10
recap_Player_LIfe = -55
included_variable = -10
[2023-01-24 18:08:15]
SAVE_PAGE = "pages/index.toml"
done_data_page = 0
page_count = 0
console_color_background = 47
recap_Number_Of_People_Killed = 10
recap_Player_LIfe = -55
included_variable = -10
[2023-01-24 18:08:17]
SAVE_PAGE = "pages/index.toml"
done_data_page = 0
page_count = 0
console_color_background = 47
recap_Number_Of_People_Killed = 10
recap_Player_LIfe = -55
included_variable = -10
[2023-01-24 18:08:18]
SAVE_PAGE = "pages/index.toml"
done_data_page = 0
page_count = 0
console_color_background = 47
recap_Number_Of_People_Killed = 10
recap_Player_LIfe = -55
included_variable = -10
